<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.5.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.184" />
    <PackageVersion Include="Squash" Version="2.1.0" />
    <PackageVersion Include="Polyfill" Version="11.4.3" />
    <PackageVersion Include="ProjectFiles" Version="1.6.0" />
    <PackageVersion Include="TUnit" Version="1.73.5" />
    <PackageVersion Include="Sbom" Version="0.3.1" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <!-- Keep at 8 to support old frameworks -->
    <PackageVersion Include="System.Collections.Immutable" Version="8.0.0" Pinned="true" />
    <PackageVersion Include="System.ValueTuple" Version="4.5.0" Pinned="true" />
    <PackageVersion Include="Verify" Version="33.3.2" />
  </ItemGroup>
</Project>